# Generated by Django 4.2.5 on 2023-10-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
    ]
